Repository PKlempe/SAM, pull requests merged in 2020-08, with the labels that each got.

#37 Feature/#17 create embeds
  bot/util/utilities.py
  requirements.txt
Labels: enhancement

#38 #36: Add a subcommand `get` to the command `modmail` and other small …
  bot/__main__.py
  bot/constants.py
  bot/moderation/moderation.py
  bot/moderation/modmail_status.py
  bot/persistence/database_connector.py
  bot/persistence/queries.py
  bot/persistence/resources/init_db.sql
  bot/test/test_db.py
  bot/util/utilities.py
Labels: enhancement

#42 #32: adds echo command
  bot/util/utilities.py
Labels: enhancement

#46 #29: Implement the new `ufind` command and the corresponding subcomma…
  bot/__init__.py
  bot/__main__.py
  bot/constants.py
  bot/feedback/__init__.py
  bot/file_management/__init__.py
  bot/fun/__init__.py
  bot/guides/__init__.py
  bot/logger/__init__.py
  bot/moderation/__init__.py
  bot/moderation/moderation.py
  bot/persistence/__init__.py
  bot/persistence/database_connector.py
  bot/role_management/__init__.py
  bot/test/__init__.py
  bot/university/__init__.py
  bot/university/university.py
  bot/util/__init__.py
  bot/util/selection_emoji.py
  bot/util/utilities.py
Labels: enhancement

#44 #43: adds logging for command and error logging to file
  .env.example
  bot/__main__.py
  bot/constants.py
  bot/logger/__init__.py
  bot/logger/logger.py
  bot/moderation/moderation.py
  bot/test/test_sample.py
  bot/university/university.py
  bot/util/utilities.py
Labels: enhancement

#47 #45: Implements the `bot presence` command to change the bots Discord…
  bot/util/utilities.py
Labels: enhancement

#51 #49: Use converters provided by discord.py where it makes sense and o…
  bot/__main__.py
  bot/logger/__init__.py
  bot/logger/logger.py
  bot/moderation/moderation.py
  bot/util/utilities.py
Labels: enhancement

#52 #48: Add admin module/cog, move some commands there and add a permiss…
  bot/__main__.py
  bot/admin/__init__.py
  bot/admin/admin.py
  bot/moderation/moderation.py
  bot/util/utilities.py
Labels: enhancement

#60 Create CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#59 #55: Implement subcommand `cogs` for command `bot` and some bug fixes
  bot/__main__.py
  bot/admin/admin.py
  bot/constants.py
  bot/university/university.py
Labels: enhancement

#62 Update SAM header
  README.md
Labels: documentation

#63 Update ReadMe
  README.md
Labels: documentation

#65 Make the header image more dark mode friendly
  README.md
Labels: documentation

#64 #39 #50: changes command cembed to embed json and adds local error ha…
  bot/admin/__init__.py
  bot/admin/admin.py
  bot/moderation/moderation.py
  bot/university/university.py
Labels: bug

#68 #61: Fix the layout of the embed for mobile devices
  bot/constants.py
  bot/moderation/moderation.py
Labels: bug

#72 #69: Add missing server feature and improve layout
  bot/util/utilities.py
Labels: bug

#71 #53: Implement multiple commands for un-/re-/loading cogs
  bot/__main__.py
  bot/admin/admin.py
  bot/university/university.py
Labels: enhancement

#75 #67: Implement report command and other small fixes
  bot/__main__.py
  bot/admin/admin.py
  bot/constants.py
  bot/moderation/moderation.py
  bot/university/university.py
Labels: enhancement

#73 Feature/#41 bot only channels
  bot/admin/admin.py
  bot/constants.py
  bot/persistence/database_connector.py
  bot/persistence/queries.py
  bot/persistence/resources/init_db.sql
Labels: enhancement

#77 #76: Add event listener to pin messages if enough users have reacted
  bot/constants.py
  bot/util/utilities.py
  requirements.txt
Labels: enhancement

#80 #79: Add "logs" directory to .gitignore
  .gitignore
Labels: enhancement

#87 Feature/#56-group-exchange
  bot/admin/admin.py
  bot/constants.py
  bot/persistence/database_connector.py
  bot/persistence/queries.py
  bot/persistence/resources/init_db.sql
  bot/university/university.py
  requirements.txt
Labels: enhancement

#86 #66: Implement `module` command and two subcommands "add/remove"
  bot/constants.py
  bot/persistence/database_connector.py
  bot/persistence/queries.py
  bot/persistence/resources/init_db.sql
  bot/university/university.py
Labels: enhancement

#91 #83: Improve log message formatting
  bot/logger/logger.py
Labels: enhancement

#93 #84: Replace all channel names with corresponding channel IDs
  bot/admin/admin.py
  bot/persistence/database_connector.py
  bot/persistence/queries.py
  bot/persistence/resources/init_db.sql
Labels: bug

#96 Create deployment git action
  .git-ftp-ignore
  .github/workflows/deployment.yml
Labels: enhancement

#95 Feature/#20 suggestions
  .pylintrc
  bot/constants.py
  bot/feedback/__init__.py
  bot/feedback/feedback.py
  bot/feedback/suggestion_status.py
  bot/persistence/database_connector.py
  bot/persistence/queries.py
  bot/persistence/resources/init_db.sql
  bot/university/university.py
Labels: enhancement
