Repository PKlempe/SAM, pull requests merged in 2020-09, with the labels that each got.

#100 Feature/#98 code cleanup
  .env.example
  bot/__main__.py
  bot/constants.py
  bot/feedback/feedback.py
  bot/moderation/moderation.py
  bot/role_management/role_management.py
  bot/university/university.py
  bot/util/utilities.py
Labels: enhancement

#104 #103: Fix some bugs and rename utility package and file
  bot/admin/admin.py
  bot/constants.py
  bot/university/university.py
  bot/utility/__init__.py
  bot/utility/selection_emoji.py
  bot/utility/utility.py
Labels: bug

#107 Improve deployment action
  .github/workflows/deployment.yml
Labels: enhancement

#109 #101: edit command
  bot/admin/admin.py
Labels: enhancement

#106 Feature/#34 moderation commands
  .env.example
  bot/admin/admin.py
  bot/constants.py
  bot/feedback/feedback.py
  bot/moderation/moderation.py
  bot/persistence/database_connector.py
  bot/persistence/queries.py
  bot/persistence/resources/init_db.sql
  bot/role_management/role_management.py
  bot/util/time_parsing.py
  requirements.txt
Labels: enhancement

#70 Add a gif to readme
  README.md
Labels: documentation

#112 #111: Replace guild instance variable with method call
  bot/admin/admin.py
  bot/constants.py
  bot/feedback/feedback.py
  bot/moderation/moderation.py
  bot/role_management/role_management.py
  bot/university/university.py
  bot/utility/utility.py
Labels: bug

#117 #115: Add a check if a role has been whitelisted and some log messages
  bot/persistence/database_connector.py
  bot/persistence/queries.py
  bot/role_management/role_management.py
Labels: bug

#118 #114: Replace requests module with async aiohttp
  bot/__main__.py
  bot/singletons.py
  bot/university/university.py
Labels: enhancement

#116 #18: Implement commands for creating/managing reaction roles
  bot/moderation/moderation.py
  bot/persistence/database_connector.py
  bot/persistence/queries.py
  bot/persistence/resources/init_db.sql
  bot/role_management/role_management.py
Labels: enhancement

#119 Feature/#108 scheduler job persistence
  bot/__main__.py
  bot/constants.py
  bot/moderation/moderation.py
  bot/singletons.py
  bot/university/university.py
Labels: enhancement

#120 #16: Add listener for sending welcome messages and small improvements
  .env.example
  bot/constants.py
  bot/moderation/moderation.py
  bot/utility/time_parsing.py
  bot/utility/utility.py
Labels: enhancement

#121 Change bot prefix
  bot/constants.py
Labels: enhancement

#123 #122: Fix the sending of mod action infos
  bot/moderation/moderation.py
  bot/university/university.py
Labels: bug

#125 Bug/#124 exchange error
  bot/__main__.py
  bot/university/university.py
Labels: bug

#127 #126: Add check if bot-only mode is activated before deleting invocat…
  .pylintrc
  bot/admin/admin.py
  bot/feedback/feedback.py
  bot/moderation/moderation.py
  bot/persistence/database_connector.py
  bot/role_management/role_management.py
  bot/university/university.py
  bot/utility/utility.py
Labels: bug
