Repository PKlempe/SAM, pull requests merged in 2021-05, with the labels that each got.

#199 Bug/#195 fix modlog message
  bot/moderation/moderation.py
Labels: bug

#201 Update requirements
  requirements.txt
Labels: dependencies

#203 Delete invokation message in error handler of the report command
  bot/moderation/moderation.py
Labels: bug

#204 Bug/#202 obsolete scheduler jobs
  bot/moderation/moderation.py
Labels: bug

#206 #205: Implement starboard-like feature in form of "highlights"
  .env.example
  bot/community/community.py
  bot/constants.py
Labels: enhancement

#208 #207: Return a message ID which can never be valid if an embed doesn'…
  bot/community/community.py
  bot/constants.py
Labels: bug

#209 Fix constant in constants.py
  bot/constants.py
Labels: bug

#210 #205: Fix for highlight detection
  bot/community/community.py
Labels: bug

#211 Small fix
  bot/community/community.py
Labels: bug
